const data = {
  statusCode: 0,
  data: {
    cacheExpiryTime: 320,
    pages: 1,
    pageIndex: 0,
    scrubber: 0,
    filters: [
      {
        type: "FilterWidget",
        title: "Cuisines",
        key: "CUISINES",
        configType: "checkbox",
        visible: 1,
        options: [
          { option: "Afghani", selected: 0, visible: 1 },
          { option: "American", selected: 0, visible: 1 },
          { option: "Andhra", selected: 0, visible: 1 },
          { option: "Arabian", selected: 0, visible: 1 },
          { option: "Asian", selected: 0, visible: 1 },
          { option: "Awadhi", selected: 0, visible: 1 },
          { option: "Bakery", selected: 0, visible: 1 },
          { option: "Barbecue", selected: 0, visible: 1 },
          { option: "Bengali", selected: 0, visible: 1 },
          { option: "Beverages", selected: 0, visible: 1 },
          { option: "Bihari", selected: 0, visible: 1 },
          { option: "Biryani", selected: 0, visible: 1 },
          { option: "Burgers", selected: 0, visible: 1 },
          { option: "Cafe", selected: 0, visible: 1 },
          { option: "Chaat", selected: 0, visible: 1 },
          { option: "Chinese", selected: 0, visible: 1 },
          { option: "Combo", selected: 0, visible: 1 },
          { option: "Continental", selected: 0, visible: 1 },
          { option: "Desserts", selected: 0, visible: 1 },
          { option: "European", selected: 0, visible: 1 },
          { option: "Fast Food", selected: 0, visible: 1 },
          { option: "French", selected: 0, visible: 1 },
          { option: "Grill", selected: 0, visible: 1 },
          { option: "Gujarati", selected: 0, visible: 1 },
          { option: "Healthy Food", selected: 0, visible: 1 },
          { option: "Home Food", selected: 0, visible: 1 },
          { option: "Hyderabadi", selected: 0, visible: 1 },
          { option: "Ice Cream", selected: 0, visible: 1 },
          { option: "Ice Cream Cakes", selected: 0, visible: 1 },
          { option: "Indian", selected: 0, visible: 1 },
          { option: "Italian", selected: 0, visible: 1 },
          { option: "Italian-American", selected: 0, visible: 1 },
          { option: "Jain", selected: 0, visible: 1 },
          { option: "Japanese", selected: 0, visible: 1 },
          { option: "Juices", selected: 0, visible: 1 },
          { option: "Kebabs", selected: 0, visible: 1 },
          { option: "Korean", selected: 0, visible: 1 },
          { option: "Lebanese", selected: 0, visible: 1 },
          { option: "Lucknowi", selected: 0, visible: 1 },
          { option: "Maharashtrian", selected: 0, visible: 1 },
          { option: "Mexican", selected: 0, visible: 1 },
          { option: "Mughlai", selected: 0, visible: 1 },
          { option: "Nepalese", selected: 0, visible: 1 },
          { option: "North Eastern", selected: 0, visible: 1 },
          { option: "North Indian", selected: 0, visible: 1 },
          { option: "Oriental", selected: 0, visible: 1 },
          { option: "Paan", selected: 0, visible: 1 },
          { option: "Pan-Asian", selected: 0, visible: 1 },
          { option: "Parsi", selected: 0, visible: 1 },
          { option: "Pastas", selected: 0, visible: 1 },
          { option: "Persian", selected: 0, visible: 1 },
          { option: "Pizzas", selected: 0, visible: 1 },
          { option: "Punjabi", selected: 0, visible: 1 },
          { option: "Salads", selected: 0, visible: 1 },
          { option: "Seafood", selected: 0, visible: 1 },
          { option: "Snacks", selected: 0, visible: 1 },
          { option: "South Indian", selected: 0, visible: 1 },
          { option: "Street Food", selected: 0, visible: 1 },
          { option: "Sushi", selected: 0, visible: 1 },
          { option: "Sweets", selected: 0, visible: 1 },
          { option: "Tandoor", selected: 0, visible: 1 },
          { option: "Thai", selected: 0, visible: 1 },
          { option: "Thalis", selected: 0, visible: 1 },
          { option: "Tibetan", selected: 0, visible: 1 },
          { option: "Waffle", selected: 0, visible: 1 },
        ],
        detail: "",
        heading: "Cuisines",
        applicable: 1,
        searchable: 1,
      },
      {
        type: "FilterWidget",
        title: "Show Restaurants With",
        key: "SHOW_RESTAURANTS_WITH",
        configType: "checkbox",
        visible: 1,
        options: [
          { option: "Offers", selected: 0, visible: 1 },
          { option: "Pure Veg", selected: 0, visible: 1 },
        ],
        detail: "",
        heading: "Offers & More",
        applicable: 1,
        searchable: 0,
      },
    ],
    sorts: [
      {
        type: "SortWidget",
        key: "RELEVANCE",
        title: "Relevance",
        selected: 1,
        visible: 1,
        defaultSelection: true,
      },
      {
        type: "SortWidget",
        key: "DELIVERY_TIME",
        title: "Delivery Time",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "RATING",
        title: "Rating",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "COST_FOR_TWO",
        title: "Cost: Low to High",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "COST_FOR_TWO_H2L",
        title: "Cost: High to Low",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
    ],
    configs: {
      ribbons: {
        PREORDER: {
          type: "PREORDER",
          text: "Preorder",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 3,
        },
        EXCLUSIVE: {
          type: "EXCLUSIVE",
          text: "Exclusive",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 2,
        },
        NEW: {
          type: "NEW",
          text: "Newly Added",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 4,
        },
        REPEAT: {
          type: "REPEAT",
          text: "Repeat",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#D53D4C",
          bottomBackgroundColor: "#B02331",
          priority: 6,
        },
        CLOUD: {
          type: "CLOUD",
          text: "Daily Menus",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 5,
        },
        PREMIUM: {
          type: "PREMIUM",
          text: "Premium",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#8a584b",
          bottomBackgroundColor: "#583229",
          priority: 7,
        },
        PROMOTED: {
          type: "PROMOTED",
          text: "Promoted",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#3a3c41",
          bottomBackgroundColor: "#1e2023",
          priority: 1,
        },
      },
      croutons: {
        RAIN: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "surge_listing_piuzrv",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "${amount} extra levied on some restaurants",
        },
        RAIN_DEFAULT: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "surge_listing_piuzrv",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "Your orders may be delayed by 5-10 mins",
        },
        SERVICEABLE_WITH_BANNER_RAIN: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "rain_crouton_4x",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "Few restaurants unserviceable due to rains",
        },
        RAIN_LOW: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "surge_listing_piuzrv",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "Your orders may be delayed by 5-10 mins",
        },
        RAIN_HIGH: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "surge_listing_piuzrv",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "Your orders may be delayed by 5-10 mins",
        },
        SPECIAL: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "surge_listing_piuzrv",
          textColor: "#ffffff",
          title: "High Demand",
          message: "Surge fee of Rs ${amount} may be applicable",
        },
      },
    },
    cards: [
      {
        cardType: "carousel",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "carousel",
          subtype: "topCarousel",
          data: {
            cards: [
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 635529,
                  creativeId: "rng/md/carousel/production/pneknawbadtvceqzwiep",
                  type: "restaurantCollectionV2",
                  link: "49301",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 304994,
                  creativeId: "rng/md/carousel/production/cwbqaumccjyifi90c9e1",
                  type: "restaurantCollectionV2",
                  link: "47670",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 181635,
                  creativeId: "rng/md/carousel/production/yparhmxrby5lv0ubsel4",
                  type: "restaurantCollectionV2",
                  link: "56413",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 607195,
                  creativeId: "rng/md/carousel/production/ifi2lbzxeu1hvsqrsip3",
                  type: "restaurantCollectionV2",
                  link: "56421",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
            ],
          },
        },
        parentWidget: false,
      },
      {
        cardType: "carousel",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "carousel",
          subtype: "openFilter",
          data: {
            cards: [
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 181684,
                  creativeId: "bkhjfipzydkoqncrxpyi",
                  type: "restaurantCollectionV2",
                  link: "11718",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  title: "Offers Near You",
                  subtitle: "0 OPTIONS",
                  restaurants: [],
                  totalCount: 0,
                  dwebOpenFilterTitle: "Offers Near You",
                  dwebOpenFilterBgColor: "#FF0000",
                  dwebOpenFilterSelectIcon: "eyperwsfhaoa5vktjtu4",
                  dwebOpenFilterDeselectIcon: "urw8usdf4mk9aywd59gq",
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 181680,
                  creativeId: "a3jqjjod5taken7dh1bs",
                  type: "restaurantCollectionV2",
                  link: "11721",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  title: "Veg Only",
                  subtitle: "0 OPTIONS",
                  restaurants: [],
                  totalCount: 0,
                  dwebOpenFilterTitle: "Vegetarian Options",
                  dwebOpenFilterBgColor: "#FF0000",
                  dwebOpenFilterSelectIcon: "qtjc8dzfexg72lug37a0",
                  dwebOpenFilterDeselectIcon: "bm8bziikwyvwqsml1clm",
                },
              },
            ],
          },
        },
        parentWidget: false,
      },
      {
        cardType: "seeAllRestaurants",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "seeAllRestaurants",
          data: {
            title: "SEE ALL",
            totalOpenRestaurants: 970,
            cards: [
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "657142",
                  name: "Punjabi Angithi (Delhi Wale)",
                  uuid: "269728de-0f94-4ea2-a78a-63f28ff53347",
                  city: "22",
                  area: "Hathibarkala",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "0a59d45ca92d85e5f63f5bc79f3dbb33",
                  cuisines: [
                    "North Indian",
                    "Chinese",
                    "Punjabi",
                    "Kebabs",
                    "Tandoor",
                  ],
                  tags: [],
                  costForTwo: 40000,
                  costForTwoString: "₹400 FOR TWO",
                  deliveryTime: 37,
                  minDeliveryTime: 37,
                  maxDeliveryTime: 37,
                  slaString: "37 MINS",
                  lastMileTravel: 5.5,
                  slugs: {
                    restaurant: "punjabi-angithi-hathibarkala-hathibarkala",
                    city: "dehradun",
                  },
                  cityState: "22",
                  address:
                    "VEGORAMA PUNJABI ANGITHI PVT LTD PARSVNATH ELEGANZA MALL 103, RAJPUR  ROAD DEHRADUN, Dehradun,  Uttarakhand-248009",
                  locality: "Rajpur Road",
                  parentId: 4464,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "Flat ₹125 off",
                    shortDescriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹249",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "₹125 OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  ribbon: [{ type: "PROMOTED" }],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 3400, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 3400,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3400",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=6323477~p=1~eid=00000187-cc42-3d5d-10e1-fa7400890113",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "5.5 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "657142",
                    deliveryTime: 37,
                    minDeliveryTime: 37,
                    maxDeliveryTime: 37,
                    lastMileTravel: 5.5,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.1",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "69769",
                  name: "Aman Vegetarian",
                  uuid: "4ef9eafb-9c6d-4e9b-b1e9-0bbd0e88f9ef",
                  city: "22",
                  area: "Paltan Bazaar",
                  totalRatingsString: "5000+ ratings",
                  cloudinaryImageId: "ygczg6efdbjietl1req7",
                  cuisines: ["North Indian", "Chinese", "Continental"],
                  tags: [],
                  costForTwo: 27500,
                  costForTwoString: "₹275 FOR TWO",
                  deliveryTime: 21,
                  minDeliveryTime: 21,
                  maxDeliveryTime: 21,
                  slaString: "21 MINS",
                  lastMileTravel: 0.4000000059604645,
                  slugs: {
                    restaurant:
                      "aman-vegetarian-paltan-bazar-near-railway-station-hathibarkala",
                    city: "dehradun",
                  },
                  cityState: "22",
                  address:
                    "Darshini Gate, Jhanda Mohalla, Paltan Bazaar,near railway station Dehradun",
                  locality: "Paltan Bazaar Road",
                  parentId: 13687,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "Flat ₹125 off",
                    shortDescriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "₹125 OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.4 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "69769",
                    deliveryTime: 21,
                    minDeliveryTime: 21,
                    maxDeliveryTime: 21,
                    lastMileTravel: 0.4000000059604645,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.9",
                  totalRatings: 5000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "69499",
                  name: "Uss Da Dhaba",
                  uuid: "be843f94-4bb1-446f-854a-fed73c5f5926",
                  city: "22",
                  area: "Race Course",
                  totalRatingsString: "10000+ ratings",
                  cloudinaryImageId: "j6w0gbsy2pdoivjjlymp",
                  cuisines: ["North Indian", "Chinese", "Continental"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 18,
                  minDeliveryTime: 18,
                  maxDeliveryTime: 18,
                  slaString: "18 MINS",
                  lastMileTravel: 0.699999988079071,
                  slugs: {
                    restaurant: "uss-da-dhaba-race-course-chukkuwala",
                    city: "dehradun",
                  },
                  cityState: "22",
                  address:
                    "Near Hotel Saurab, 3 Court Road, Race Course, Dehradun",
                  locality: "Court Road",
                  parentId: 13693,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "Flat ₹125 off",
                    shortDescriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "₹125 OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.6 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "69499",
                    deliveryTime: 18,
                    minDeliveryTime: 18,
                    maxDeliveryTime: 18,
                    lastMileTravel: 0.699999988079071,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.7",
                  totalRatings: 10000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "212001",
                  name: "Biryani By Kilo",
                  uuid: "c7875289-6b81-4814-b1e6-f10bf38a68a0",
                  city: "22",
                  area: "Ballupur",
                  totalRatingsString: "5000+ ratings",
                  cloudinaryImageId: "x7uyth98klateehaavbt",
                  cuisines: [
                    "Biryani",
                    "Hyderabadi",
                    "North Indian",
                    "Kebabs",
                    "Mughlai",
                    "Desserts",
                  ],
                  tags: [],
                  costForTwo: 70000,
                  costForTwoString: "₹700 FOR TWO",
                  deliveryTime: 45,
                  minDeliveryTime: 45,
                  maxDeliveryTime: 45,
                  slaString: "45 MINS",
                  lastMileTravel: 3,
                  slugs: {
                    restaurant: "biryani-by-kilo-kishan-nagar-kishan-nagar",
                    city: "dehradun",
                  },
                  cityState: "22",
                  address:
                    "Mahendra Vihar, Ballupur Road, Mahendra Vihar, Mahinder Vihar, Khurbura Mohalla, Dehradun, Uttarakhand, India",
                  locality: "Kishan nagar",
                  parentId: 130,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "Flat ₹125 off",
                    shortDescriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹249",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "₹125 OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  ribbon: [{ type: "PROMOTED" }],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=6545532~p=4~eid=00000187-cc42-3d5d-10e1-fa750089042f",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "3 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "212001",
                    deliveryTime: 45,
                    minDeliveryTime: 45,
                    maxDeliveryTime: 45,
                    lastMileTravel: 3,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.0",
                  totalRatings: 5000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "88166",
                  name: "Nath'S Chinese",
                  uuid: "5e2f426b-1f57-4c80-a45a-4a9bdec46030",
                  city: "22",
                  area: "Khurbura",
                  totalRatingsString: "10000+ ratings",
                  cloudinaryImageId: "fsm15mqsuninmtb6twec",
                  cuisines: ["North Indian", "Chinese", "Tandoor"],
                  tags: [],
                  costForTwo: 15000,
                  costForTwoString: "₹150 FOR TWO",
                  deliveryTime: 23,
                  minDeliveryTime: 23,
                  maxDeliveryTime: 23,
                  slaString: "23 MINS",
                  lastMileTravel: 0.30000001192092896,
                  slugs: {
                    restaurant:
                      "naths-chinese-race-course-race-course-dehradun",
                    city: "dehradun",
                  },
                  cityState: "22",
                  address: "278, Lakhi Bagh, Dehradun",
                  locality: "Lakkhi Bagh",
                  parentId: 13608,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "FLAT125 off",
                    shortDescriptionList: [
                      {
                        meta: "FLAT125 off | Use FLATDEAL",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "FLAT125 off | Use FLATDEAL",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "₹125 OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use FLATDEAL",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "FLAT125 off | Use FLATDEAL",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.3 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "88166",
                    deliveryTime: 23,
                    minDeliveryTime: 23,
                    maxDeliveryTime: 23,
                    lastMileTravel: 0.30000001192092896,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.0",
                  totalRatings: 10000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "69500",
                  name: "Rajdhani Chicken Point",
                  uuid: "39567d38-19cc-43e9-94d9-60132c7b6937",
                  city: "22",
                  area: "Race Course",
                  totalRatingsString: "10000+ ratings",
                  cloudinaryImageId: "jkkhgvwcjvpfheq8ftbv",
                  cuisines: ["North Indian", "Chinese", "Continental"],
                  tags: [],
                  costForTwo: 27500,
                  costForTwoString: "₹275 FOR TWO",
                  deliveryTime: 26,
                  minDeliveryTime: 26,
                  maxDeliveryTime: 26,
                  slaString: "26 MINS",
                  lastMileTravel: 1,
                  slugs: {
                    restaurant: "rajdhani-chicken-point-race-course-chukkuwala",
                    city: "dehradun",
                  },
                  cityState: "22",
                  address:
                    "Gandhi Road, Near Fire Station ,Race Course, Dehradun",
                  locality: "Gandhi Road",
                  parentId: 13692,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "Flat ₹125 off",
                    shortDescriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "₹125 OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "69500",
                    deliveryTime: 26,
                    minDeliveryTime: 26,
                    maxDeliveryTime: 26,
                    lastMileTravel: 1,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.8",
                  totalRatings: 10000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "532213",
                  name: "Chilli'Z Restro",
                  uuid: "0b828188-33d3-4bfb-ab57-f901539b273a",
                  city: "22",
                  area: "Prem Nagar",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "mzsuzzznrww2mpzwk27d",
                  cuisines: ["North Indian", "Chinese", "Snacks", "Beverages"],
                  tags: [],
                  costForTwo: 30000,
                  costForTwoString: "₹300 FOR TWO",
                  deliveryTime: 20,
                  minDeliveryTime: 20,
                  maxDeliveryTime: 20,
                  slaString: "20 MINS",
                  lastMileTravel: 2,
                  slugs: {
                    restaurant:
                      "chilliz-restro-(patel-nagar)-patel-nagar-patel-nagar",
                    city: "dehradun",
                  },
                  cityState: "22",
                  address: "75/4,arya tower,patel nagar,Dehradun 248001",
                  locality: "Saharanpur Road",
                  parentId: 13645,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "Flat ₹125 off",
                    shortDescriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "₹125 OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  ribbon: [{ type: "PROMOTED" }],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=6302449~p=10~eid=00000187-cc42-3d5d-10e1-fa7700890a45",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "532213",
                    deliveryTime: 20,
                    minDeliveryTime: 20,
                    maxDeliveryTime: 20,
                    lastMileTravel: 2,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "3.8",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "75724",
                  name: "Doon Darbar",
                  uuid: "a1660262-e320-4680-a585-7147bdd54295",
                  city: "22",
                  area: "Race Course",
                  totalRatingsString: "10000+ ratings",
                  cloudinaryImageId: "hhjgw9fofqopwnioxtaj",
                  cuisines: ["North Indian", "Mughlai"],
                  tags: [],
                  costForTwo: 27500,
                  costForTwoString: "₹275 FOR TWO",
                  deliveryTime: 24,
                  minDeliveryTime: 24,
                  maxDeliveryTime: 24,
                  slaString: "24 MINS",
                  lastMileTravel: 1,
                  slugs: {
                    restaurant: "doon-darbar-paltan-bazaar-chukkuwala",
                    city: "dehradun",
                  },
                  cityState: "22",
                  address: "43, Gandhi Road, Paltan Bazaar, Dehradun",
                  locality: "Gandhi Road",
                  parentId: 13207,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "Flat ₹125 off",
                    shortDescriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "₹125 OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "75724",
                    deliveryTime: 24,
                    minDeliveryTime: 24,
                    maxDeliveryTime: 24,
                    lastMileTravel: 1,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.7",
                  totalRatings: 10000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "89064",
                  name: "Ahuja Chinese Food Court",
                  uuid: "79187865-c0b3-463a-b832-d7e3159a6f8a",
                  city: "22",
                  area: "Race Course",
                  totalRatingsString: "10000+ ratings",
                  cloudinaryImageId: "uvzfjwcslztz1tzjlzfg",
                  cuisines: ["Chinese"],
                  tags: [],
                  costForTwo: 15000,
                  costForTwoString: "₹150 FOR TWO",
                  deliveryTime: 22,
                  minDeliveryTime: 22,
                  maxDeliveryTime: 22,
                  slaString: "22 MINS",
                  lastMileTravel: 1.100000023841858,
                  slugs: {
                    restaurant:
                      "ahuja-chinese-food-court-chandan-nagar-race-course-dehradun",
                    city: "dehradun",
                  },
                  cityState: "22",
                  address: "57/B , Rest Camp, Tyagi Road, Dehradun",
                  locality: "Tyagi Road",
                  parentId: 13607,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "FLAT125 off",
                    shortDescriptionList: [
                      {
                        meta: "FLAT125 off | Use FLATDEAL",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "FLAT125 off | Use FLATDEAL",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "₹125 OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use FLATDEAL",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "FLAT125 off | Use FLATDEAL",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1.1 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "89064",
                    deliveryTime: 22,
                    minDeliveryTime: 22,
                    maxDeliveryTime: 22,
                    lastMileTravel: 1.100000023841858,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.5",
                  totalRatings: 10000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "84229",
                  name: "Punjabi Dhaba",
                  uuid: "317a42f9-5111-400c-a254-1e2a8b677d64",
                  city: "22",
                  area: "Paltan Bazaar",
                  totalRatingsString: "10000+ ratings",
                  cloudinaryImageId: "yyrjmyajqhyjq6mp1gha",
                  cuisines: ["North Indian"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 24,
                  minDeliveryTime: 24,
                  maxDeliveryTime: 24,
                  slaString: "24 MINS",
                  lastMileTravel: 0.6000000238418579,
                  slugs: {
                    restaurant:
                      "punjabi-dhaba-prince-chowk-race-course-dehradun",
                    city: "dehradun",
                  },
                  cityState: "22",
                  address: "59, Gandhi Road, Prince Chowk, Dehradun",
                  locality: "Gandhi Road",
                  parentId: 1476,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "FLAT125 off",
                    shortDescriptionList: [
                      {
                        meta: "FLAT125 off | Use FLATDEAL",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "FLAT125 off | Use FLATDEAL",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "₹125 OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use FLATDEAL",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "FLAT125 off | Use FLATDEAL",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.6 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "84229",
                    deliveryTime: 24,
                    minDeliveryTime: 24,
                    maxDeliveryTime: 24,
                    lastMileTravel: 0.6000000238418579,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.7",
                  totalRatings: 10000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "584793",
                  name: "Ginger n Garlic",
                  uuid: "43d0c0da-ad0f-489c-bff0-2ad24d4907d4",
                  city: "22",
                  area: "Patel Nagar",
                  totalRatingsString: "100+ ratings",
                  cloudinaryImageId: "178e14b2134ecaf26c94ae6f4b4da0fc",
                  cuisines: ["North Indian", "Chinese", "Thalis"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 19,
                  minDeliveryTime: 19,
                  maxDeliveryTime: 19,
                  slaString: "19 MINS",
                  lastMileTravel: 0.30000001192092896,
                  slugs: {
                    restaurant:
                      "nath's-restaurant-by-nath's-chinese-hathibarkala-hathibarkala",
                    city: "dehradun",
                  },
                  cityState: "22",
                  address: "278, Lakhi Bagh, Dehradun",
                  locality: "Arhat Bazaar",
                  parentId: 349995,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "60% off",
                    shortDescriptionList: [
                      {
                        meta: "60% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "60% off up to ₹120 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "60% OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "60% off up to ₹120 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.3 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "584793",
                    deliveryTime: 19,
                    minDeliveryTime: 19,
                    maxDeliveryTime: 19,
                    lastMileTravel: 0.30000001192092896,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.0",
                  totalRatings: 100,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "95048",
                  name: "Walk In Woods (Sahastradhara Road)",
                  uuid: "6ef373fe-8610-42d8-bc3f-acc75dbbfd05",
                  city: "22",
                  area: "Chironwali",
                  totalRatingsString: "10000+ ratings",
                  cloudinaryImageId: "zgkkairefnvffmiq77dh",
                  cuisines: [
                    "North Indian",
                    "Chinese",
                    "Desserts",
                    "Beverages",
                  ],
                  tags: [],
                  costForTwo: 27500,
                  costForTwoString: "₹275 FOR TWO",
                  deliveryTime: 36,
                  minDeliveryTime: 36,
                  maxDeliveryTime: 36,
                  slaString: "36 MINS",
                  lastMileTravel: 6.199999809265137,
                  slugs: {
                    restaurant: "walk-in-woods-sahasradhara-sahasradhara",
                    city: "dehradun",
                  },
                  cityState: "22",
                  address:
                    "K32 Mandakni Vihar, Sahastradhara Road, Chironwali, Dehradun",
                  locality: "Sahastradhara Road",
                  parentId: 359024,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "Flat ₹125 off",
                    shortDescriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "₹125 OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
                        discountType: "Flat",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  ribbon: [{ type: "PROMOTED" }],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 4200, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 4200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "4200",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=6302322~p=13~eid=00000187-cc42-3d5d-10e1-fa7800890d3e",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "6.1 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "95048",
                    deliveryTime: 36,
                    minDeliveryTime: 36,
                    maxDeliveryTime: 36,
                    lastMileTravel: 6.199999809265137,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.1",
                  totalRatings: 10000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "390906",
                  name: "Annapurna Vegetarian",
                  uuid: "1340c86e-b776-41a4-a8d1-a53d7b94ab95",
                  city: "22",
                  area: "Paltan Bazaar",
                  totalRatingsString: "100+ ratings",
                  cloudinaryImageId: "lybjdo30aewxq6pplsym",
                  cuisines: ["North Indian"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 25,
                  minDeliveryTime: 25,
                  maxDeliveryTime: 25,
                  slaString: "25 MINS",
                  lastMileTravel: 0.4000000059604645,
                  slugs: {
                    restaurant: "aman-vegetarian-chukkuwala-chukkuwala",
                    city: "dehradun",
                  },
                  cityState: "22",
                  address: "14,Darshani Gate,Dehradun",
                  locality: "Ajit Prasad Nagar",
                  parentId: 241045,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "40% off",
                    shortDescriptionList: [
                      {
                        meta: "40% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "40% off up to ₹80 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "40% OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "40% off up to ₹80 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.4 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "390906",
                    deliveryTime: 25,
                    minDeliveryTime: 25,
                    maxDeliveryTime: 25,
                    lastMileTravel: 0.4000000059604645,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.8",
                  totalRatings: 100,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "69062",
                  name: "Naveen Vegetarian (Jhanda Bazar)",
                  uuid: "f2e8b784-af70-464c-a104-7186e6e75207",
                  city: "22",
                  area: "Paltan Bazaar",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "trajbpkhdfqf8bee5vvf",
                  cuisines: ["Indian", "Chinese"],
                  tags: [],
                  costForTwo: 27500,
                  costForTwoString: "₹275 FOR TWO",
                  deliveryTime: 21,
                  minDeliveryTime: 21,
                  maxDeliveryTime: 21,
                  slaString: "21 MINS",
                  lastMileTravel: 0.4000000059604645,
                  slugs: {
                    restaurant: "naveen-vegetarian-paltan-bazaar-chukkuwala",
                    city: "dehradun",
                  },
                  cityState: "22",
                  address:
                    "Darshini Gate, Dhamawala Mohalla, Paltan Bazaar, Dehradun",
                  locality: "Arhat Bazaar Road",
                  parentId: 13700,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.4 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "69062",
                    deliveryTime: 21,
                    minDeliveryTime: 21,
                    maxDeliveryTime: 21,
                    lastMileTravel: 0.4000000059604645,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.1",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "648862",
                  name: "Rasam Restaurant",
                  uuid: "48e4d580-096a-4a61-889f-faca9c95ce62",
                  city: "22",
                  area: "Rajpur Road",
                  totalRatingsString: "50+ ratings",
                  cloudinaryImageId: "0ff7f5ee8d60de2e4e065f322519addf",
                  cuisines: ["South Indian", "Snacks"],
                  tags: [],
                  costForTwo: 25000,
                  costForTwoString: "₹250 FOR TWO",
                  deliveryTime: 36,
                  minDeliveryTime: 36,
                  maxDeliveryTime: 36,
                  slaString: "36 MINS",
                  lastMileTravel: 4.300000190734863,
                  slugs: {
                    restaurant: "rasam-restaurant-hathibarkala-hathibarkala",
                    city: "dehradun",
                  },
                  cityState: "22",
                  address:
                    "101, Rajpur Road, Opposite Garhwal Mandal Vikas Nigam Limited, Dehradun, Uttarakhand",
                  locality: "",
                  parentId: 253484,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "60% off",
                    shortDescriptionList: [
                      {
                        meta: "60% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "60% off up to ₹120 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "60% OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "60% off up to ₹120 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  ribbon: [{ type: "PROMOTED" }],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 2400, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 2400,
                    message: "",
                    title: "Delivery Charge",
                    amount: "2400",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=6482339~p=16~eid=00000187-cc42-3d5d-10e1-fa7900891068",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "4.3 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "648862",
                    deliveryTime: 36,
                    minDeliveryTime: 36,
                    maxDeliveryTime: 36,
                    lastMileTravel: 4.300000190734863,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.2",
                  totalRatings: 50,
                  new: false,
                },
                subtype: "basic",
              },
            ],
            totalRestaurants: 970,
          },
          subtype: "personalized",
        },
        parentWidget: false,
      },
    ],
    nextPageFetch: 0,
  },
  tid: "33faf0f3-47c0-492b-b27b-a48cd638e1cc",
  sid: "6rq65b4e-0095-4670-a4f3-79b705f2a5e7",
  deviceId: "c53bd5df-67b9-6f6b-346a-5bbb669bba44",
  csrfToken: "98mOPx0HRv0W-mMqOEVe8pAKJhb72h8Y5TmCF1Qw",
};
